//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int AutoId { get; set; }
        public string Number { get; set; }
        public int ProducerId { get; set; }
        public byte[] Photo { get; set; }
        public string uName { get; set; }
        public string LastName { get; set; }
    
        public virtual Producer Producer { get; set; }
    }
}
